M48
; DRILL file {KiCad 6.0.8-f2edbf62ab~116~ubuntu20.04.1} date mar 11 oct 2022 23:56:37
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-11T23:56:37-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8-f2edbf62ab~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.700
%
G90
G05
T1
X116.0Y-67.5
X116.0Y-138.5
X194.5Y-68.0
X194.75Y-138.75
T0
M30
