/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM.h"
#include "Bootloadable_1.h"
#include "LED_OnB.h"
#include "LED_OnB_aliases.h"
#include "Clock_1.h"
#include "DUTY_INT.h"
#include "Pin_Ext1.h"
#include "Pin_Ext1_aliases.h"
#include "Pin_SWOnB.h"
#include "Pin_SWOnB_aliases.h"
#include "SW_INT.h"
#include "Pin_Ext2.h"
#include "Pin_Ext2_aliases.h"
#include "PERIODO_INT.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

