/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Bootloadable_1.h"
#include "PWM.h"
#include "IDAC.h"
#include "ADC.h"
#include "AMux.h"
#include "Val_Peri.h"
#include "Val_Peri_aliases.h"
#include "Val_duty.h"
#include "Val_duty_aliases.h"
#include "Val_Vout.h"
#include "Val_Vout_aliases.h"
#include "IDAC_Pos.h"
#include "IDAC_Pos_aliases.h"
#include "IDAC_Neg.h"
#include "IDAC_Neg_aliases.h"
#include "PIN_SW.h"
#include "PIN_SW_aliases.h"
#include "LCD.h"
#include "Clock_1.h"
#include "PWM_INT.h"
#include "SW_INT.h"
#include "PWM_V0.h"
#include "PWM_V0_aliases.h"
#include "Timer_1.h"
#include "TIMER_INT.h"
#include "ADC_INTAux.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

