/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Bootloadable_1.h"
#include "IDAC_1.h"
#include "Iout_neg.h"
#include "Iout_neg_aliases.h"
#include "SW1_Vout.h"
#include "SW1_Vout_aliases.h"
#include "ACT_Vout.h"
#include "AMux_1.h"
#include "Iout_pos.h"
#include "Iout_pos_aliases.h"
#include "Nivel_Vout.h"
#include "Nivel_Vout_aliases.h"
#include "LCD.h"
#include "DutyC_Vout.h"
#include "DutyC_Vout_aliases.h"
#include "PERIODO_Vout.h"
#include "PERIODO_Vout_aliases.h"
#include "PWM.h"
#include "Clock_1.h"
#include "PWMComp_INT.h"
#include "PWMPeri_INT.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

