# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\ESCRITORIO\Tesis MIB\Proyecto de Tesis\electroestimulador\PSoC\PRUEBAS\SCB_Bootloader\Bootloadable Toggle LEDs por HW.cydsn\Bootloadable Toggle LEDs por HW.cyprj
# Date: Tue, 17 Nov 2020 17:19:00 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for D:\ESCRITORIO\Tesis MIB\Proyecto de Tesis\electroestimulador\PSoC\PRUEBAS\SCB_Bootloader\Bootloadable Toggle LEDs por HW.cydsn\TopDesign\TopDesign.cysch
# Project: D:\ESCRITORIO\Tesis MIB\Proyecto de Tesis\electroestimulador\PSoC\PRUEBAS\SCB_Bootloader\Bootloadable Toggle LEDs por HW.cydsn\Bootloadable Toggle LEDs por HW.cyprj
# Date: Tue, 17 Nov 2020 17:18:56 GMT
